{"ray": {"sid": "59995a44bc124f718e958734ff535671", "uid": null, "qid": "54ee83ad508a4cd98b16dccbbc147ece", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [54ee83ad508a4cd98b16dccbbc147ece]\nTraceback (most recent call last):\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/openfabric_pysdk/app/worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n  File \"/home/youseef/openfabric/openfabric-ai-software-engineer/openfabric-ai-software-engineer/main.py\", line 80, in execute\n    answer = qa_model(text, context)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"/home/youseef/openfabric/openfabric-ai-software-engineer/openfabric-ai-software-engineer/main.py\", line 50, in forward\n    outputs = self.model.generate(**inputs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/utils/_contextlib.py\", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/generation/utils.py\", line 1593, in generate\n    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/generation/utils.py\", line 742, in _prepare_encoder_decoder_kwargs_for_generation\n    model_kwargs[\"encoder_outputs\"]: ModelOutput = encoder(**encoder_kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py\", line 1110, in forward\n    layer_outputs = layer_module(\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py\", line 694, in forward\n    self_attention_outputs = self.layer[0](\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py\", line 601, in forward\n    attention_output = self.SelfAttention(\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py\", line 531, in forward\n    scores = torch.matmul(\ntorch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.69 GiB. GPU 0 has a total capacty of 3.81 GiB of which 2.89 GiB is free. Including non-PyTorch memory, this process has 940.00 MiB memory in use. Of the allocated memory 833.76 MiB is allocated by PyTorch, and 38.24 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n", "created_at": "2023-12-14T01:37:08.534017"}], "status": "FAILED", "created_at": "2023-12-14T01:36:56.112123", "updated_at": "2023-12-14T01:37:08.535513", "finished": true}, "in": {"text": ["What is the capital of France"]}, "out": {}}