{"ray": {"sid": "e8c35153f7aa46c2b4268c06f51b359a", "uid": null, "qid": "a174b6a87d534da9a902bb293afebe87", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [a174b6a87d534da9a902bb293afebe87]\nTraceback (most recent call last):\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/openfabric_pysdk/app/worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n  File \"/home/youseef/openfabric/openfabric-ai-software-engineer/openfabric-ai-software-engineer/main.py\", line 68, in execute\n    context_model, qa_model = model_loading()\n  File \"/home/youseef/openfabric/openfabric-ai-software-engineer/openfabric-ai-software-engineer/main.py\", line 62, in model_loading\n    model_b = QAModel()\n  File \"/home/youseef/openfabric/openfabric-ai-software-engineer/openfabric-ai-software-engineer/main.py\", line 42, in __init__\n    self.model = AutoModelForSeq2SeqLM.from_pretrained(\"google/flan-t5-large\").to(self.device)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1695, in __getattr__\n    raise AttributeError(f\"'{type(self).__name__}' object has no attribute '{name}'\")\nAttributeError: 'QAModel' object has no attribute 'device'\n", "created_at": "2023-12-14T03:06:33.768492"}], "status": "FAILED", "created_at": "2023-12-14T03:06:23.464011", "updated_at": "2023-12-14T03:06:33.828316", "finished": true}, "in": {"text": ["What is the capital of Egypt?", "How many elements in the periodic table?", "What is the normal distribution"]}, "out": {}}